# ID211677083
# -*- coding: utf-8 -*-
"""Introductory Exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oy-nrOykiIg2ZqWvDOTCHVub0fa0p4b0

# Python Introductory Exercise

Define a variable called `user_and_pass` and enter the value `False`.
"""



"""Write code that will ask the user to enter his name without spaces and store the name in a variable named `user_name`."""

user_and_pass = False

"""Write code that will check if `user_name` contains spaces.

1.   If `user_name` is correct,

* Type a code that will ask the user to enter a password that is exactly 8 characters long.

*   Type a code that will check if the password is indeed 8 characters long (use the `len` function), if so enter the value `True` in the `user_and_pass`.




"""



"""Write code that will check if `user_and_pass` is set to `True`,

* if `user_and_pass` is `True` ask the user to enter their username and password, insert the user input to a new variables.

* than check if the username **and** password are correct:

1.   If so, print to the user "Welcome Professor"

2.   If not, print to the user that the details entered are incorrect.
"""

