# ID211677083
# -*- coding: utf-8 -*-
"""Introductory Exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oy-nrOykiIg2ZqWvDOTCHVub0fa0p4b0

# Python Introductory Exercise

Define a variable called `user_and_pass` and enter the value `False`.
"""

user_and_pass = False

"""Write code that will ask the user to enter his name without spaces and store the name in a variable named `user_name`."""

user_name = input("Please enter your name without spaces at all.")

"""Write code that will check if `user_name` contains spaces."""

user_name_valid = 0

while user_name_valid == 0:
    if " " in user_name:
        print("There is space")
        user_name = input("Please enter your name without spaces at all.")
    else:
        print("There is not space. The user name is valid!")
        user_name_valid = 1

"""


1.   If `user_name` is correct,

* Type a code that will ask the user to enter a password that is exactly 8 characters long.

*   Type a code that will check if the password is indeed 8 characters long (use the `len` function), if so enter the value `True` in the `user_and_pass`.

"""

password = input(print("Please enter 8 digits password:"))
while len(password) != 8:
    print("Passowrd is not valid")
    password = input(print("Please enter 8 digits password:"))
print("Password is valid")
user_and_pass = True


"""Write code that will check if `user_and_pass` is set to `True`,

* if `user_and_pass` is `True` ask the user to enter their username and password, insert the user input to a new variables.

* than check if the username **and** password are correct:

1.   If so, print to the user "Welcome Professor"

2.   If not, print to the user that the details entered are incorrect.
"""
if user_and_pass == True:
    print("Let's make a doublecheck.")
    user_name_DC = input("Please enter your name without spaces at all.")
    password_DC = input(print("Please enter 8 digits password:"))

    if user_name_DC == user_name and password_DC == password:
        print("Welcome Proffesor!")
    else:
        print("An error was occured.")

